/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppPedidoNovoRouteImport } from './routes/_app.pedido.novo'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa/webhook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidoNovoRoute = AppPedidoNovoRouteImport.update({
  id: '/pedido/novo',
  path: '/pedido/novo',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa/webhook',
  path: '/api/public/wa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/pedido/novo': typeof AppPedidoNovoRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/pedido/novo': typeof AppPedidoNovoRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pedido/novo': typeof AppPedidoNovoRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/pedido/novo'
    | '/api/public/wa/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/pedido/novo' | '/api/public/wa/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/pedido/novo'
    | '/api/public/wa/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedido/novo': {
      id: '/_app/pedido/novo'
      path: '/pedido/novo'
      fullPath: '/pedido/novo'
      preLoaderRoute: typeof AppPedidoNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/wa/webhook': {
      id: '/api/public/wa/webhook'
      path: '/api/public/wa/webhook'
      fullPath: '/api/public/wa/webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPedidoNovoRoute: typeof AppPedidoNovoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPedidoNovoRoute: AppPedidoNovoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
